# If you want test this requests. You need to install VsCode Extension REST Client
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### teste 1
GET http://localhost:3000/users

### teste 1
GET http://localhost:3000/user?name=Otavio Benedicto

### teste 2
POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"New Username",
    "job":"Web Developer"
}

### teste 3
DELETE http://localhost:3000/users?name=New Username

### teste 4
PUT http://localhost:3000/users?id=2
Content-Type: application/json

{
    "job":"Desenvolvedor Junior"
}

### teste 5
GET http://localhost:3000/users/access?name=João Oliveira
